# **Pandas**
Data Manipulation

In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.DataFrame({
    'population':[1430000000, 242000000, 173000000, 22000000, 31000000],
    'GDP':[3400000000000, 375000000000, 460000000000, 84000000000, 40000000000],
    'Surface Area':[3287263, 881913, 148460, 65610, 147516],
    'HDI':[0.913, 0.888, 0.916, 0.8,0.1],
    'Continents':['Australia', 'Pakistan', 'Nepal', 'India', 'Tajikistan']



})

In [8]:
print(df)

   population            GDP  Surface Area    HDI  Continents
0  1430000000  3400000000000       3287263  0.913   Australia
1   242000000   375000000000        881913  0.888    Pakistan
2   173000000   460000000000        148460  0.916       Nepal
3    22000000    84000000000         65610  0.800       India
4    31000000    40000000000        147516  0.100  Tajikistan

In [10]:
df

   population            GDP  Surface Area    HDI  Continents
0  1430000000  3400000000000       3287263  0.913   Australia
1   242000000   375000000000        881913  0.888    Pakistan
2   173000000   460000000000        148460  0.916       Nepal
3    22000000    84000000000         65610  0.800       India
4    31000000    40000000000        147516  0.100  Tajikistan

In [12]:
df.shape

(5, 5)

In [ ]:
# shape = tells about rows and columns

In [13]:
df.index =['Australia', 'Pakistan', 'Nepal', 'India', 'Tajikistan']

In [14]:
print(df)

            population            GDP  Surface Area    HDI  Continents
Australia   1430000000  3400000000000       3287263  0.913   Australia
Pakistan     242000000   375000000000        881913  0.888    Pakistan
Nepal        173000000   460000000000        148460  0.916       Nepal
India         22000000    84000000000         65610  0.800       India
Tajikistan    31000000    40000000000        147516  0.100  Tajikistan

In [15]:
df.columns

Index(['population', 'GDP', 'Surface Area', 'HDI', 'Continents'], dtype='object')

In [16]:
df.index

Index(['Australia', 'Pakistan', 'Nepal', 'India', 'Tajikistan'], dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Australia to Tajikistan
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   population    5 non-null      int64
 1   GDP           5 non-null      int64
 2   Surface Area  5 non-null      int64
 3   HDI           5 non-null      float64
 4   Continents    5 non-null      object
dtypes: float64(1), int64(3), object(1)
memory usage: 240.0+ bytes

In [18]:
df.size

25

In [20]:
df.describe()

         population           GDP  Surface Area      HDI
count  5.000000e+00  5.000000e+00  5.000000e+00  5.00000
mean   3.796000e+08  8.718000e+11  9.061524e+05  0.72340
std    5.946338e+08  1.424843e+12  1.371716e+06  0.35165
min    2.200000e+07  4.000000e+10  6.561000e+04  0.10000
25%    3.100000e+07  8.400000e+10  1.475160e+05  0.80000
50%    1.730000e+08  3.750000e+11  1.484600e+05  0.88800
75%    2.420000e+08  4.600000e+11  8.819130e+05  0.91300
max    1.430000e+09  3.400000e+12  3.287263e+06  0.91600

In [21]:
df.dtypes

population        int64
GDP               int64
Surface Area      int64
HDI             float64
Continents       object
dtype: object

In [22]:
df.dtypes.value_counts()

int64      3
float64    1
object     1
Name: count, dtype: int64

In [23]:
df.iloc[0]

population         1430000000
GDP             3400000000000
Surface Area          3287263
HDI                     0.913
Continents          Australia
Name: Australia, dtype: object

In [24]:
df.iloc[2]

population         173000000
GDP             460000000000
Surface Area          148460
HDI                    0.916
Continents             Nepal
Name: Nepal, dtype: object

In [25]:
df.loc['India']

population         22000000
GDP             84000000000
Surface Area          65610
HDI                     0.8
Continents            India
Name: India, dtype: object

In [26]:
df.iloc[-5]

population         1430000000
GDP             3400000000000
Surface Area          3287263
HDI                     0.913
Continents          Australia
Name: Australia, dtype: object

In [28]:
df[['population','GDP']]

            population            GDP
Australia   1430000000  3400000000000
Pakistan     242000000   375000000000
Nepal        173000000   460000000000
India         22000000    84000000000
Tajikistan    31000000    40000000000

In [29]:
df[1:4]

          population           GDP  Surface Area    HDI Continents
Pakistan   242000000  375000000000        881913  0.888   Pakistan
Nepal      173000000  460000000000        148460  0.916      Nepal
India       22000000   84000000000         65610  0.800      India

In [30]:
df.loc['Pakistan':'India','population']

Pakistan    242000000
Nepal       173000000
India        22000000
Name: population, dtype: int64

In [32]:
df.loc['Australia':'Nepal',['population','GDP','HDI']]

           population            GDP    HDI
Australia  1430000000  3400000000000  0.913
Pakistan    242000000   375000000000  0.888
Nepal       173000000   460000000000  0.916

In [39]:
df.loc[['Pakistan','India'],['population','GDP']]

          population           GDP
Pakistan   242000000  375000000000
India       22000000   84000000000

In [40]:
df.iloc[[0,1,-1]]

            population            GDP  Surface Area    HDI  Continents
Australia   1430000000  3400000000000       3287263  0.913   Australia
Pakistan     242000000   375000000000        881913  0.888    Pakistan
Tajikistan    31000000    40000000000        147516  0.100  Tajikistan