**EDA Session#1 - Learned about Pandas, Dataframes, Series, did data manipulation and studied best practises.**

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
days_of_week=pd.Series(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])

In [ ]:
days_of_week

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
dtype: object

In [ ]:
population=pd.Series([31.1,111.1,12.2,111.2,1888.9])

In [ ]:
population

0      31.1
1     111.1
2      12.2
3     111.2
4    1888.9
dtype: float64

In [ ]:
population.name="G5 Population in millions"

In [ ]:
print(population)

0      31.1
1     111.1
2      12.2
3     111.2
4    1888.9
Name: G5 Population in millions, dtype: float64

In [ ]:
population

0      31.1
1     111.1
2      12.2
3     111.2
4    1888.9
Name: G5 Population in millions, dtype: float64

In [ ]:
#In order to find data type
population.dtype

dtype('float64')

In [ ]:
days_of_week.dtype
# o = object

dtype('O')

In [ ]:
population.values

array([  31.1,  111.1,   12.2,  111.2, 1888.9])

In [ ]:
population[0]

np.float64(31.1)

In [ ]:
population[2]

np.float64(12.2)

In [ ]:
population.values[0]

np.float64(31.1)

In [ ]:
population.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
population.index=["Pakistan","Bangladesh","China","Iran","USA"]

In [ ]:
print(population)

Pakistan        31.1
Bangladesh     111.1
China           12.2
Iran           111.2
USA           1888.9
Name: G5 Population in millions, dtype: float64

In [ ]:
population_g7=

In [ ]:
g7_countries = {
    'Canada': 38.2,
    'France': 65.5,
    'Germany': 83.2,
    'Italy': 59.1,
    'Japan': 125.7,
    'United Kingdom': 67.3,
    'United States': 331.9
}

g7_population = pd.Series(g7_countries, name='G7 Population in millions')
print(g7_population)

Canada             38.2
France             65.5
Germany            83.2
Italy              59.1
Japan             125.7
United Kingdom     67.3
United States     331.9
Name: G7 Population in millions, dtype: float64

In [ ]:
section={
    "Hamza":23,
    "Salman":20,
    "iKram":30,
    "Yahya":21
}
class_fellows=pd.Series(section, name="School friends")
print (class_fellows)

Hamza     23
Salman    20
iKram     30
Yahya     21
Name: School friends, dtype: int64

In [ ]:
POPULATION=pd.Series([1,2,3,4,5],
                     index=["a","b","c","d","e"],
                            name="alphabets and numbers")

In [ ]:
print(POPULATION)

a    1
b    2
c    3
d    4
e    5
Name: alphabets and numbers, dtype: int64

In [ ]:
pd.Series(population,index=["USA","Bangladesh"])

USA           1888.9
Bangladesh     111.1
Name: G5 Population in millions, dtype: float64

In [ ]:
population.iloc[0]

np.float64(31.1)

In [ ]:
population.iloc[-1]

np.float64(1888.9)

In [ ]:
population[["Bangladesh","Iran"]]

Bangladesh    111.1
Iran          111.2
Name: G5 Population in millions, dtype: float64

In [ ]:
population["Pakistan":"USA"]

Pakistan        31.1
Bangladesh     111.1
China           12.2
Iran           111.2
USA           1888.9
Name: G5 Population in millions, dtype: float64

In [ ]:
population > 70

Pakistan      False
Bangladesh     True
China         False
Iran           True
USA            True
Name: G5 Population in millions, dtype: bool

In [ ]:
population.mean()

np.float64(430.9)

In [ ]:
population.std()

816.301699740972

In [ ]:
population*1000000

Pakistan      3.110000e+07
Bangladesh    1.111000e+08
China         1.220000e+07
Iran          1.112000e+08
USA           1.888900e+09
Name: G5 Population in millions, dtype: float64

In [ ]:
np.log(population)

Pakistan      3.437208
Bangladesh    4.710431
China         2.501436
Iran          4.711330
USA           7.543750
Name: G5 Population in millions, dtype: float64

In [ ]:
population[["Pakistan","Iran"]].mean()

np.float64(71.15)

In [ ]:
population["Pakistan":"USA"].mean()

np.float64(430.9)

In [ ]:
population["Pakistan"]=100

In [ ]:
print(population)

Pakistan       100.0
Bangladesh     111.1
China           12.2
Iran           111.2
USA           1888.9
Name: G5 Population in millions, dtype: float64

In [ ]:
population.iloc[-1]=400

In [ ]:
print(population)

Pakistan      100.0
Bangladesh    111.1
China          12.2
Iran          111.2
USA           400.0
Name: G5 Population in millions, dtype: float64

In [ ]:
population_new=population.copy()

In [ ]:
print(population_new)

Pakistan      100.0
Bangladesh    111.1
China          12.2
Iran          111.2
USA           400.0
Name: G5 Population in millions, dtype: float64